m1 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial1/MGate.csv", FALSE)
m2 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial2/MGate.csv", FALSE)
m3 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial3/MGate.csv", FALSE)
m4 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial4/MGate.csv", FALSE)
m5 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial5/MGate.csv", FALSE)
m6 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial6/MGate.csv", FALSE)
m7 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial7/MGate.csv", FALSE)
m8 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial8/MGate.csv", FALSE)
m9 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial9/MGate.csv", FALSE)
m10 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial10/MGate.csv", FALSE)
h1 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial1/HGate.csv", FALSE)
h2 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial2/HGate.csv", FALSE)
h3 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial3/HGate.csv", FALSE)
h4 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial4/HGate.csv", FALSE)
h5 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial5/HGate.csv", FALSE)
h6 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial6/HGate.csv", FALSE)
h7 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial7/HGate.csv", FALSE)
h8 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial8/HGate.csv", FALSE)
h9 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial9/HGate.csv", FALSE)
h10 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial10/HGate.csv", FALSE)
s1 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial1/SGate.csv", FALSE)
s2 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial2/SGate.csv", FALSE)
s3 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial3/SGate.csv", FALSE)
s4 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial4/SGate.csv", FALSE)
s5 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial5/SGate.csv", FALSE)
s6 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial6/SGate.csv", FALSE)
s7 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial7/SGate.csv", FALSE)
s8 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial8/SGate.csv", FALSE)
s9 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial9/SGate.csv", FALSE)
s10 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial10/SGate.csv", FALSE)
mp1 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial1/MPGate.csv", FALSE)
mp2 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial2/MPGate.csv", FALSE)
mp3 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial3/MPGate.csv", FALSE)
mp4 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial4/MPGate.csv", FALSE)
mp5 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial5/MPGate.csv", FALSE)
mp6 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial6/MPGate.csv", FALSE)
mp7 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial7/MPGate.csv", FALSE)
mp8 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial8/MPGate.csv", FALSE)
mp9 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial9/MPGate.csv", FALSE)
mp10 <- read.csv(file = "C:/Users/Joey/Desktop/TestData/CROW/Best Trials CROW/DCAmpComparison/trial10/MPGate.csv", FALSE)

m1DF <- csvToDF(m1)
m2DF <- csvToDF(m2)
m3DF <- csvToDF(m3)
m4DF <- csvToDF(m4)
m5DF <- csvToDF(m5)
m6DF <- csvToDF(m6)
m7DF <- csvToDF(m7)
m8DF <- csvToDF(m8)
m9DF <- csvToDF(m9)
m10DF <- csvToDF(m10)
h1DF <- csvToDF(h1)
h2DF <- csvToDF(h2)
h3DF <- csvToDF(h3)
h4DF <- csvToDF(h4)
h5DF <- csvToDF(h5)
h6DF <- csvToDF(h6)
h7DF <- csvToDF(h7)
h8DF <- csvToDF(h8)
h9DF <- csvToDF(h9)
h10DF <- csvToDF(h10)
s1DF <- csvToDF(s1)
s2DF <- csvToDF(s2)
s3DF <- csvToDF(s3)
s4DF <- csvToDF(s4)
s5DF <- csvToDF(s5)
s6DF <- csvToDF(s6)
s7DF <- csvToDF(s7)
s8DF <- csvToDF(s8)
s9DF <- csvToDF(s9)
s10DF <- csvToDF(s10)
mp1DF <- csvToDF(mp1)
mp2DF <- csvToDF(mp2)
mp3DF <- csvToDF(mp3)
mp4DF <- csvToDF(mp4)
mp5DF <- csvToDF(mp5)
mp6DF <- csvToDF(mp6)
mp7DF <- csvToDF(mp7)
mp8DF <- csvToDF(mp8)
mp9DF <- csvToDF(mp9)
mp10DF <- csvToDF(mp10)

m1AVGDF <- movingAverageDF(m1DF, 10)
m2AVGDF <- movingAverageDF(m2DF, 10)
m3AVGDF <- movingAverageDF(m3DF, 10)
m4AVGDF <- movingAverageDF(m4DF, 10)
m5AVGDF <- movingAverageDF(m5DF, 10)
m6AVGDF <- movingAverageDF(m6DF, 10)
m7AVGDF <- movingAverageDF(m7DF, 10)
m8AVGDF <- movingAverageDF(m8DF, 10)
m9AVGDF <- movingAverageDF(m9DF, 10)
m10AVGDF <- movingAverageDF(m10DF, 10)
h1AVGDF <- movingAverageDF(h1DF, 10)
h2AVGDF <- movingAverageDF(h2DF, 10)
h3AVGDF <- movingAverageDF(h3DF, 10)
h4AVGDF <- movingAverageDF(h4DF, 10)
h5AVGDF <- movingAverageDF(h5DF, 10)
h6AVGDF <- movingAverageDF(h6DF, 10)
h7AVGDF <- movingAverageDF(h7DF, 10)
h8AVGDF <- movingAverageDF(h8DF, 10)
h9AVGDF <- movingAverageDF(h9DF, 10)
h10AVGDF <- movingAverageDF(h10DF, 10)
s1AVGDF <- movingAverageDF(s1DF, 10)
s2AVGDF <- movingAverageDF(s2DF, 10)
s3AVGDF <- movingAverageDF(s3DF, 10)
s4AVGDF <- movingAverageDF(s4DF, 10)
s5AVGDF <- movingAverageDF(s5DF, 10)
s6AVGDF <- movingAverageDF(s6DF, 10)
s7AVGDF <- movingAverageDF(s7DF, 10)
s8AVGDF <- movingAverageDF(s8DF, 10)
s9AVGDF <- movingAverageDF(s9DF, 10)
s10AVGDF <- movingAverageDF(s10DF, 10)
mp1AVGDF <- movingAverageDF(mp1DF, 10)
mp2AVGDF <- movingAverageDF(mp2DF, 10)
mp3AVGDF <- movingAverageDF(mp3DF, 10)
mp4AVGDF <- movingAverageDF(mp4DF, 10)
mp5AVGDF <- movingAverageDF(mp5DF, 10)
mp6AVGDF <- movingAverageDF(mp6DF, 10)
mp7AVGDF <- movingAverageDF(mp7DF, 10)
mp8AVGDF <- movingAverageDF(mp8DF, 10)
mp9AVGDF <- movingAverageDF(mp9DF, 10)
mp10AVGDF <- movingAverageDF(mp10DF, 10)

m1AVGSlopeDF <- slopeDF(m1AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
m2AVGSlopeDF <- slopeDF(m2AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
m3AVGSlopeDF <- slopeDF(m3AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
m4AVGSlopeDF <- slopeDF(m4AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
m5AVGSlopeDF <- slopeDF(m5AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
m6AVGSlopeDF <- slopeDF(m6AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
m7AVGSlopeDF <- slopeDF(m7AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
m8AVGSlopeDF <- slopeDF(m8AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
m9AVGSlopeDF <- slopeDF(m9AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
m10AVGSlopeDF <- slopeDF(m10AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
h1AVGSlopeDF <- slopeDF(h1AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
h2AVGSlopeDF <- slopeDF(h2AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
h3AVGSlopeDF <- slopeDF(h3AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
h4AVGSlopeDF <- slopeDF(h4AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
h5AVGSlopeDF <- slopeDF(h5AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
h6AVGSlopeDF <- slopeDF(h6AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
h7AVGSlopeDF <- slopeDF(h7AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
h8AVGSlopeDF <- slopeDF(h8AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
h9AVGSlopeDF <- slopeDF(h9AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))
h10AVGSlopeDF <- slopeDF(h10AVGDF, c("Node51", "Node50", "Node49", "Node48", "Node47", "Node46", "Node45", "Node44", "Node43", "Node42", "Node41"))

mh1 <- m3hCalcDF(m1DF,h1DF)
mh2 <- m3hCalcDF(m2DF,h2DF)
mh3 <- m3hCalcDF(m3DF,h3DF)
mh4 <- m3hCalcDF(m4DF,h4DF)
mh5 <- m3hCalcDF(m5DF,h5DF)
mh6 <- m3hCalcDF(m6DF,h6DF)
mh7 <- m3hCalcDF(m7DF,h7DF)
mh8 <- m3hCalcDF(m8DF,h8DF)
mh9 <- m3hCalcDF(m9DF,h9DF)
mh10 <- m3hCalcDF(m10DF,h10DF)

mh1AVGDF <- m3hCalcDF(m1AVGDF, h1AVGDF)
mh2AVGDF <- m3hCalcDF(m2AVGDF, h2AVGDF)
mh3AVGDF <- m3hCalcDF(m3AVGDF, h3AVGDF)
mh4AVGDF <- m3hCalcDF(m4AVGDF, h4AVGDF)
mh5AVGDF <- m3hCalcDF(m5AVGDF, h5AVGDF)
mh6AVGDF <- m3hCalcDF(m6AVGDF, h6AVGDF)
mh7AVGDF <- m3hCalcDF(m7AVGDF, h7AVGDF)
mh8AVGDF <- m3hCalcDF(m8AVGDF, h8AVGDF)
mh9AVGDF <- m3hCalcDF(m9AVGDF, h9AVGDF)
mh10AVGDF <- m3hCalcDF(m10AVGDF, h10AVGDF)

